# -*- coding: utf-8 -*-
{
    "name": "BigCommerce Connector",
    "summary": "Base framework for BigCommerce integration",
    "version": "18.0.2.0.0",
    "author": "Your Company",
    "website": "https://www.example.com",
    "category": "Sales",
    "license": "LGPL-3",
    "depends": [
        "base",
        "product",
        "sale",
        "stock",
        "contacts",
        "delivery",
        "mail",
        "account",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/bigcommerce_cron_data.xml",
        "views/bigcommerce_dashboard_action.xml",
        "views/bigcommerce_connector_views.xml",
        "views/field_mapping_views.xml",
        "views/field_mapping_test_wizard_views.xml",
        "views/bigcommerce_mapping_message_wizard_views.xml",
        "views/category_binding_views.xml",
        "views/product_binding_views.xml",
        "views/customer_binding_views.xml",
        "views/order_binding_views.xml",
        "views/bigcommerce_log_views.xml",
        "views/bigcommerce_webhook_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bigcommerce_connector/static/src/xml/bigcommerce_dashboard_templates.xml",
            "bigcommerce_connector/static/src/js/bigcommerce_dashboard.js",
            "bigcommerce_connector/static/src/css/bigcommerce_dashboard.css",
        ],
    },
    "installable": True,
    "application": True,
}
